{% set name = "xmidas" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xmidas-{{ version }}.tar.gz
  sha256: 116d2f893d4896efb36d283bba9a11bbedc71d51ff3e391c45ba01a5d7859ad4

build:
  number: 0
  noarch: python
  entry_points:
    - xmidas = xmidas.main:start_xmidas
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - h5py
    - numpy
    - packaging
    - pandas
    - pyqtgraph >=0.12.2
    - pyshortcuts
    - pystackreg
    - python >=3.7
    - scikit-image
    - scikit-learn
    - scipy >=1.7
    - silx
    - tifffile
    - xraylarch >=0.9.57
    - pyqt
    - opencv

test:
  imports:
    - xmidas
    - xmidas.uis
    - xmidas.main
  commands:
    - xmidas --help

about:
  home: https://github.com/NSLS-II/xmidas
  summary: X-Ray Multimodal Image Data Analysis Software
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dmgav
    - mrakitin
    - XYangXRay
